---
- name: Add EPEL repository
  yum:
    name: epel-release
    state: present
    
- name: upgrade all packages
  yum:
    name: '*'
    state: latest

- name: Install basic packages
  package:
    name: ['wget','unzip','curl']
    state: present

- name: Install Java 8 CentOS
  yum:
    name: java-1.8.0-openjdk
    state: present

- name: Add tomcat group
  group:
    name: tomcat

- name: Add tomcat user
  user:
    name: tomcat
    group: tomcat
    home: /usr/share/tomcat
    createhome: no
    system: yes

- name: Download Tomcat
  get_url:
    url: "{{ tomcat_archive_url }}"
    dest: "{{ tomcat_archive_dest }}"

- name: Create a tomcat directory
  file:
    path: /usr/share/tomcat
    state: directory
    owner: tomcat
    group: tomcat

- name: Extract tomcat archive
  unarchive:
    src: "{{ tomcat_archive_dest }}"
    dest: /usr/share/tomcat
    owner: tomcat
    group: tomcat
    remote_src: yes
    extra_opts: "--strip-components=1"
    creates: /usr/share/tomcat/bin

- name: Copy tomcat service file
  template:
    src: templates/tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  when: ansible_service_mgr == "systemd"

- name: Start and enable tomcat
  service:
    daemon_reload: yes
    name: tomcat
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"
  
- name: Configure Tomcat users
  template: src=tomcat-users.xml.j2 dest=/usr/share/tomcat/conf/
  notify: restart tomcat
  
- name: Configure Tomcat host-manager
  template: src=context.xml dest=/usr/share/tomcat/webapps/host-manager/META-INF/
  notify: restart tomcat
  
- name: Configure Tomcat manager
  template: src=context.xml dest=/usr/share/tomcat/webapps/manager/META-INF/
  notify: restart tomcat

- name: Start and enable firewalld
  service:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_service_mgr == "systemd"

- name: Open tomcat port on the firewall
  firewalld:
    port: 8080/tcp
    permanent: true
    state: enabled
    immediate: yes
  when: ansible_service_mgr == "systemd"
